name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 17
          cache: "yarn"
          registry-url: "https://registry.npmjs.org"
      - run: yarn
      - run: yarn run parcel build ./src/core.ts --no-source-maps
      - run: mv index.js core.js
      - run: yarn run tsc -p .
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{secrets.NPM_TOKEN}}
          access: public
          check-version: true
